import {
  EXPENSE_CATEGORIES,
  GOAL_PRIORITIES,
  GOAL_STATUSES,
  INCOME_CATEGORIES,
  TRANSACTION_SOURCES,
  TRANSACTION_TYPES,
} from '@lifebalance/shared/types'

export {
  EXPENSE_CATEGORIES,
  INCOME_CATEGORIES,
  TRANSACTION_TYPES,
  TRANSACTION_SOURCES,
  GOAL_PRIORITIES,
  GOAL_STATUSES,
}

export const CONNECTION_PLATFORMS = ['line', 'discord'] as const
